spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 0
